FROM python:3.11-slim as develop-stage
RUN apt-get update && \
  apt-get install -y build-essential libpq-dev && \
  rm -rf /var/lib/apt/lists/*
RUN pip install poetry
WORKDIR /app
COPY poetry.lock pyproject.toml /app/
RUN poetry config virtualenvs.create false && \
  poetry install --no-root --no-interaction --no-ansi --without dev
COPY . /app

FROM develop-stage as build-stage
RUN poetry run python build.py

FROM node:18.12-alpine as production-stage
WORKDIR /app
COPY package*.json ./
RUN yarn global add vite

COPY . /app
COPY --from=build-stage /app/.build /app/.build

RUN yarn
RUN yarn dev

EXPOSE 5173
