[tool.black]
line-length = 120

[tool.coverage.run]
omit = ["*tests/*"]

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "raise NotImplementedError", "def __repr__"]
show_missing = true

[tool.mypy]
plugins = []

[tool.pytest.ini_options]
addopts = "--cov=press --cov-report=html"
